# This is the configuration file for generating data.

# If spaces option is not given then it assumes we want to run on all spaces
# inside pro_spaces directory
# Otherwise place space names in as a yaml list.

# spaces:
#   - 22_x=(-1, 1)_y=(-1, 1)_z=(-1, 1).npy

iteration_max: 500

# Currently only nom is implemented. TODO implement uniform distribution.
poi_method: nom

# Random seeds to run each experiment on.
seeds:
  - 1
  # - 2
  # - 0xDEADBEEF
  # - 0xFFEEB111
  # - 0x12FF9877

# exploration constant
c: 1.2

# Number of PROs to choose
target_size: 4

# The resolution factor controls how quickly we sample the target space craft
# For example, if res_factor=2 then we sample at every other measurement
resolution_factor: 12